---
- name: "Gather facts using junos module"
  hosts: junos
  connection: local
  gather_facts: no
  
  tasks:
  
  - junos_facts: 
      host={{ inventory_hostname }}
      username=admin
      password=inoclab1
    register: junos
  - debug: var=junos
