---
- hosts: localhost

  tasks:
  - file: path=version_report.txt state=absent
  - file: path=version_report.txt state=touch

- name: "Gather facts using junos module"
  hosts: junos
  
  tasks:
  
  - junos_facts:
      provider: "{{netconf}}"
    register: junos
  - lineinfile:
      dest: version_report.txt
      line: "{{inventory_hostname}} : {{junos.ansible_facts.version}}"
