---
- hosts: junos
  gather_facts: no
  tasks:
  - raw: "show arp no-resolve"
    register: show
  - local_action: >
      copy content={{show.stdout}} 
           dest=./{{inventory_hostname}}.arp.txt
